Batch downloading
NinjaCheetah/NUSGet pull request #6
Opened 2024-10-19 16:08 UTC by yeah-its-gloria

This PR adds batch downloading using NUS scripts, which is useful for things like [WiFi modding Wii Minis](https://github.com/webhdx/WiiMini-SDRST/wiki/Software-guide-%28WiFi-module-installed%29).

2024-10-20 05:09 UTC, NinjaCheetah commented
Hey, thanks for the contribution! 

I should hopefully be able to take at look at this tomorrow, but I just wanted to let you know that I've seen it, and at a quick glance it looks good! Adding back NUSD's script support to NUSGet has definitely been on my agenda for a bit, but I can only handle working with GUIs in short bursts so I hadn't gotten there yet.  I very much appreciate the help with it!

2024-10-20 21:41 UTC, NinjaCheetah requested changes
Looks pretty good overall!

I do have one concern, which is that if any title listed in the script is invalid, that causes an error when you get to that entry and then the bulk download is aborted. It would probably be good to validate all of the TIDs and version numbers against the database before triggering the bulk download, just to make sure that you won't hit any invalid values during the operation.

I also would maybe consider switching away from NUSD's use of hexadecimal version numbers, or supporting both hex and decimal version numbers, because those unfamiliar with the script format (that would include me, lol) but know that it's TID and then version would probably assume it's the decimal version number since that's all the interface displays, which will either not work or potentially download an unexpected version if the numbers align right.

Feedback on my feedback is definitely welcome if you disagree with anything!

2024-10-20 21:41 UTC, NinjaCheetah commented on NUSGet.py
> +        self.ui.log_text_browser.setText(self.log_text)
Personally I would want to make a new `lock_ui` method for these lines above, because there are now two methods that need to disable all of these elements and that's just a lot to duplicate.

2024-10-20 21:41 UTC, NinjaCheetah commented on NUSGet.py
> +                QMessageBox.critical(self, app.translate("MainWindow", "Script Failure"), app.translate("MainWindow", "This script is invalid."), buttons=QMessageBox.StandardButton.Ok, defaultButton=
Might want to make this and the other error a bit more descriptive, just to make it clearer what the user needs to do to fix their script.

2024-10-20 21:44 UTC, NinjaCheetah commented on qt/py/ui_MainMenu.py
> +## Created by: Qt User Interface Compiler version 6.8.0
This isn't a review but hey PySide6 being updated to Qt 6.8.0 means that Breeze loads correctly, so that's neat! Looks much better than Fusion tends to.
![image](https://github.com/user-attachments/assets/ec4ee9c9-91df-4706-9378-2032481126b5)

2024-10-21 10:32 UTC, yeah-its-gloria commented on qt/py/ui_MainMenu.py
> +## Created by: Qt User Interface Compiler version 6.8.0
I'm on macOS and it seems not to like the large text blocks for some reason, they're cut off, but I don't think this should be fixed as part of this PR tbh
![image](https://github.com/user-attachments/assets/be6f8d3a-5e21-411d-b304-6d0b282f9e2a)

2024-10-21 12:04 UTC, yeah-its-gloria commented
I've decided against supporting decimal numbers in this PR, since the format is pretty old, kinda terrible and not even used very often (this is for pure convenience batch downloading IOSes primarily). In the future, I'd say it'd be better to fully replace NUSD's old script format with something like a table of titles in a JSON file instead.

2024-10-21 12:05 UTC, yeah-its-gloria commented on qt/py/ui_MainMenu.py
> +## Created by: Qt User Interface Compiler version 6.8.0
Ok I think I solved this with some messing around all funny, let me know how you feel about how this looks (the `Run Script` button was always meant to look small like it does here, I forgot to keep it that way, oops)
![image](https://github.com/user-attachments/assets/b41741b4-9d76-422b-ab53-a58270deeb33)

2024-10-21 17:39 UTC, NinjaCheetah commented on qt/py/ui_MainMenu.py
> +## Created by: Qt User Interface Compiler version 6.8.0
I think that looks good! I'll check it over on Linux and probably Windows as well just to be sure the margins work as expected, but I think it should be fine.

2024-10-21 17:45 UTC, NinjaCheetah commented
Yeah that's probably for the best to not try and work with this format more lol. 

I'm looking to finally push out v1.2.0 soon, because there have been a decent number of improvements that I want to be generally available now, especially with more eyes on NUSGet recently. Most likely I'll give everything a once-over after this PR is merged and then release v1.2.0, and after that I'll look into making a JSON-based format for scripts because yeah that would absolutely be better.

2024-10-21 20:50 UTC, NinjaCheetah commented on qt/py/ui_MainMenu.py
> +## Created by: Qt User Interface Compiler version 6.8.0
Update now that I've seen it on Linux: the "vWii Title Settings" gets a little too squished, at least with the Breeze theme. It looked okay under macOS but the way Breeze does padding makes it feel a little claustrophobic.
![image](https://github.com/user-attachments/assets/87569fb2-c5fd-423b-b7fc-84b72ac44560)

2024-10-21 21:17 UTC, NinjaCheetah requested changes
Noted two spots where there's some trouble (one being about the UI in that comment thread, not sure how that'll appear relative to this review), but looks good beyond that!

2024-10-21 21:17 UTC, NinjaCheetah commented on NUSGet.py
> +                                    break
This code works well for typical regioned titles, but the System Menu is a strange case where it's regioned but doesn't end with an XX, and that seems to break this parsing. The code falls back on "World", but then that's not a valid reason so it throws a KeyError when it tries to iterate over the versions in that region.

2024-10-21 21:23 UTC, yeah-its-gloria commented on NUSGet.py
> +                                    break
Fixed 👍

2024-10-21 21:30 UTC, yeah-its-gloria commented on qt/py/ui_MainMenu.py
> +## Created by: Qt User Interface Compiler version 6.8.0
I can't really figure out how to fix the problem with macOS without making it look this way tbh

2024-10-21 21:33 UTC, NinjaCheetah commented on qt/py/ui_MainMenu.py
> +## Created by: Qt User Interface Compiler version 6.8.0
Hmm... it's especially weird because it *is* wrapping the vWii checkbox. I wonder if maybe I did something weird when I was setting up word wrapping for the checkbox text, since they have to be separate labels.

2024-10-21 21:46 UTC, NinjaCheetah approved these changes

2024-10-21 21:47 UTC, yeah-its-gloria commented on qt/py/ui_MainMenu.py
> +## Created by: Qt User Interface Compiler version 6.8.0
I tried resizing the mai window to a larger base size and everything fits now, but it looks funny on smaller screens (mostly < 1080p screens, which are arguably uncommon), here's a screenshot of running it on an iPad mini through Sidecar
<img width="1133" alt="image" src="https://github.com/user-attachments/assets/cbdc816c-21bd-4264-8bdf-4a856d102ddb">

2024-10-21 21:51 UTC, NinjaCheetah commented
I can't guarantee this will change anything, but could you try this build of the interface on macOS? I messed with the constraints some and at least on Linux and in Qt Designer it shows all of the text as wrapping now.
[ui_MainMenu.zip](https://github.com/user-attachments/files/17467241/ui_MainMenu.zip)

2024-10-22 02:11 UTC, NinjaCheetah commented
Spent an honestly ridiculous amount of time in Qt Designer on my old 2010 MacBook tinkering with just about every bit of spacing and constraints I could find, and I *finally* found something that works correctly. This fixes the spacing on macOS (which fixes the text getting cut off) while retaining the original size of everything, and still looks good on Linux (I'm sure it's fine on Windows as well, but if that's not right then oh well, I'll check it out and fix it before v1.2.0). Hopefully this looks good on your end like it did for me, I was working under macOS 12 so it probably should be identical under something newer.

Here's the UI file I ended up with:
[MainMenu.zip](https://github.com/user-attachments/files/17468939/MainMenu.zip)

2024-10-22 07:48 UTC, yeah-its-gloria commented
Yep, works just fine on macOS 15 on my M2 MacBook Air too. I copied your work into this PR.

2024-10-22 10:55 UTC, NinjaCheetah commented
Awesome! In that case, I think that's everything, so I'll go ahead and merge this PR. Thanks!

2024-10-22 10:55 UTC, merged

2024-10-22 12:17 UTC, yeah-its-gloria commented
🫡